### ISSUE TITLE
I can provide some dictionary sources, in yaml

### ISSUE THREAD

**Issue by ple1n** [ikey4u/wikit#10]
https://github.com/planetoryd/OpenMdicts

@ikey4u

**Comment by ikey4u** [comment]
Thank you. 

These dictionary sources are copyrighted. If one uses them personally, it may has no problem. However, if we distribute them in public, we may have troubles.

In fact, wikit supports you create doctionary from some other format dictionary (mdx, for example), or the specified text format (see readme on project homepage). 

And further,  I am planning to make some bulitin dictionaries which have public domain copyright, such as webster1913, if you are interested in these work, welcome to contribute.

**Comment by ple1n** [comment]
Fair enough, and I agree. I would distribute these things in some other ways then
