### ISSUE TITLE
Does not run on Wayland natively

### ISSUE THREAD

**Issue by Congee** [ikey4u/wikit#8]
Because global shortcuts is only supported on X11. See: https://github.com/tauri-apps/tao/issues/248

Is there a way to disable global shortcuts as a workaround?

**Comment by ikey4u** [comment]
Hi, I have disabled `global-shortcut-all` feature of tauri, can you have a try of branch [fix-wayland](https://github.com/ikey4u/wikit/tree/fix-wayland)?

**Comment by Congee** [comment]
Thank you for that fix attempt. I still see the same error.

**Comment by Congee** [comment]
Do you have a contributing guide for developers to participate in? Maybe I can submit a patch easily if there's a guide that can walk me through the code :grin:

**Comment by ikey4u** [comment]
Sorry, there is no contribution guide yet. The project consists of three parts, the core library (wikit/core),the cli tool (wikit/cli),the desktop gui (wikit/desktop). You can start with the desktop gui code (required basic knownledge of svelte and tauri framework). No constrict on contributing, feel free to PR and I will review the PR before merging. Thank you.

**Comment by ikey4u** [comment]
I have tried v0.0.1-beta.2 on ubuntu 20.04 with wayland window environment installed, it works without any problem. As a result, it maybe not a problem of wayland.

**Comment by Congee** [comment]
I guess you have Xwayland running so tauri actually still uses X. Anyway, it's an upstream problem. If it cannot be simply worked around by disable the global shortcuts feature, I can dive into the code for some luck ;)

**Comment by ikey4u** [comment]
Can you give your linux environment? Maybe i can try to reproduce the issue locally.

**Comment by Congee** [comment]
I really appreciate your willing to help but I've been using NixOS. Though it's reproducible but not easy to get started with.

I would suggest you kill Xwayland or manually set the environment variable for X to be empty like `DISPLAY=''` to run wikit desktop

```
$ DISPLAY='' wikit
```

**Comment by ikey4u** [comment]
I have no wayland environment to test wikit dictionary, as a result, I will close this issue. Anyone who have the same issue can reopen or @ me directly.
